### ISSUE TITLE
Group and Note Widgets

### ISSUE THREAD

**Issue by Strainy** [grosser/kennel#82]
It would be great if we could use the "Group" and "Note" widgets on our dashboards. They help organise and explain more complex dashboards.

**Comment by grosser** [comment]
how do they not work atm ?
does a `rake kennel:import` dump them ?
do they need dashboards api ?

**Comment by Strainy** [comment]
`rake kennel:import` just seems to drop the groups unfortunately.
It did import notes from my dashboard, but when attempting to update DataDog the validation failed as the notes don't include a `requests` property. It ends up imported the note as a graph and validating it as such.

**Comment by grosser** [comment]
kk, will take a look soon ™️

**Comment by Strainy** [comment]
Thanks Michael! 😸

**Comment by dongxiaohe** [comment]
@grosser Hey, buddy, how much work for adding this. If it takes some effort, our team can probably help for that. :)

**Comment by grosser** [comment]
It's either easy and just a tiny fix for the existing dash.rb or it requires a new dashboard model, in which case I'd prefer to scrap/covert dash.rb since I don't want 2 models doing the same.
First step would be looking into import result and see if it has all required fields, we can also pair on this, since some fresh eyes would be good anyway :)

**Comment by grosser** [comment]
https://github.com/grosser/kennel/pull/80
